[package]
name = "vc-slint"
version = "0.1.0"
authors = ["Jaydar"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i-slint-backend-winit = "1.3.2"
slint = "1.0"
windows-sys = {version = "0.52.0",features = ["Win32_Foundation","Win32_UI_WindowsAndMessaging"] }
winit = "0.29.4"

[build-dependencies]
slint-build = "1.0"
