import { VerticalBox, LineEdit, HorizontalBox, ScrollView, SpinBox, CheckBox, StyleMetrics } from "std-widgets.slint";

import { Button } from "../base/fluent/button.slint";
import { ComboBox } from "../base/fluent/combobox.slint";
import { ColorComboBox } from "../base/fluent/color-combobox.slint";
import { AppData } from "../store.slint";
import { Page } from "../widget/Page.slint";

export component AddPage inherits Page {

    in-out property <int> cover-mode : 0;
    in-out property <string> cover-text: "";
    in-out property <string> cover-family: "";
    in-out property <int> cover-size: 18;
    in-out property <color> cover-color: #f34235;
    in-out property <color> cover-bg-color: #363f45;
    in-out property <int> cover-duration: 3;
    in-out property <string> cover-path: "";
    in-out property <string> video-path: "";

    ScrollView {
        width: 100%;
        height: 100%;
        vertical-stretch: 1;
        VerticalLayout{
            spacing: 10px;
            vertical-stretch: 1;
            HorizontalLayout{
                height: 32px;
                width: 100%;
                spacing: 10px;
                Text {
                    vertical-alignment: center;
                    font-size: 13px;
                    font-weight: 400;
                    text: "选择模式:";
                }
                ComboBox{
                    height: 32px;
                    model: ["使用文字","使用图片"];
                    current-index: cover-mode;
                    selected(str) => {
                        root.cover-mode = self.current-index;
                    }
                }
            }

            Rectangle {
                height: 5px;
            }

            // 文字
            if (cover-mode == 0): HorizontalLayout{
                height: 32px;
                width: 100%;
                spacing: 10px;
                Text {
                    vertical-alignment: center;
                    font-size: 13px;
                    font-weight: 400;
                    text: "文字封面:";
                }
                LineEdit {
                    text: root.cover-text;
                    placeholder-text: "请输入封面文字";
                    enabled:true;
                }
            }

            if (cover-mode == 0): HorizontalLayout{
                height: 32px;
                width: 100%;
                spacing: 10px;
                Text {
                    vertical-alignment: center;
                    font-size: 13px;
                    font-weight: 400;
                    text: "选择字体:";
                }
                ComboBox{
                    height: 32px;
                    model: ["黑体","宋体","楷体"];
                    current-index: cover-mode;
                }
            }
            
            if (cover-mode == 0): HorizontalLayout{
                height: 32px;
                width: 100%;
                spacing: 10px;
                Text {
                    vertical-alignment: center;
                    font-size: 13px;
                    font-weight: 400;
                    text: "设置字号:";
                }
                SpinBox {
                    enabled: true;
                    height: 32px;
                    value: root.cover-size;
                }
            }

            if (cover-mode == 0): HorizontalLayout{
                height: 32px;
                width: 100%;
                spacing: 10px;
                Text {
                    vertical-alignment: center;
                    font-size: 13px;
                    font-weight: 400;
                    text: "文字颜色:";
                }
                ColorComboBox {
                    enabled: true;
                    height: 32px;
                    model: [#f34235,#e81d62,#363f45,#9b26af,#6639b6,#3e50b4,#2095f2,#02a8f3,#00bbd3,#009587,#4bae4f,#8ac249,#ccdb38,#feea3a,#fec006,#fe9700,#fe5621,#785447,#9d9d9d,#5f7c8a];
                    current-value: root.cover-color;
                }
            }

            if (cover-mode == 0): HorizontalLayout{
                height: 32px;
                width: 100%;
                spacing: 10px;
                Text {
                    vertical-alignment: center;
                    font-size: 13px;
                    font-weight: 400;
                    text: "背景颜色:";
                }
                ColorComboBox {
                    enabled: true;
                    height: 32px;
                    model: [#f34235,#e81d62,#363f45,#9b26af,#6639b6,#3e50b4,#2095f2,#02a8f3,#00bbd3,#009587,#4bae4f,#8ac249,#ccdb38,#feea3a,#fec006,#fe9700,#fe5621,#785447,#9d9d9d,#5f7c8a];
                    current-value: root.cover-bg-color;
                }
            }


            if (cover-mode == 1): VerticalLayout {
                spacing: 5px;
                // height: 64px;
                HorizontalLayout{
                    height: 32px;
                    width: 100%;
                    spacing: 10px;
                    Text {
                        vertical-alignment: center;
                        font-size: 13px;
                        font-weight: 400;
                        text: "选择图片:";
                    }
                    Button {
                        horizontal-stretch: 1;
                        height: 32px;
                        text: "选择图片";
                        icon: @image-url("../assets/svg/file.svg");
                    }
                }
                if (root.cover-path != ""): Text {
                    height: 16px;
                    vertical-alignment: center;
                    wrap: no-wrap;
                    overflow: elide;
                    font-size: 12px;
                    color: StyleMetrics.textedit-text-color-disabled;
                    text: root.cover-path;
                }
            }

            HorizontalLayout{
                height: 32px;
                width: 100%;
                spacing: 10px;
                Text {
                    vertical-alignment: center;
                    font-size: 13px;
                    font-weight: 400;
                    text: "持续时间:";
                }
                SpinBox {
                    enabled: true;
                    height: 32px;
                    value: cover-duration;
                }
            }


            Rectangle {
                height: 5px;
            }

            VerticalLayout {
                height: 32px;
                spacing: 5px;
                // height: 64px;
                HorizontalLayout{
                    height: 100%;
                    width: 100%;
                    spacing: 10px;
                    Text {
                        vertical-alignment: center;
                        font-size: 13px;
                        font-weight: 400;
                        text: "选择视频:";
                    }
                    Button {
                        horizontal-stretch: 1;
                        height: 32px;
                        text: "文件";
                        icon: @image-url("../assets/svg/file.svg");
                    }
                    Button {
                        horizontal-stretch: 1;
                        height: 32px;
                        text: "文件夹";
                        icon: @image-url("../assets/svg/folder.svg");
                    }
                }
                
                if (root.video-path != ""): Text {
                    height: 16px;
                    vertical-alignment: center;
                    text: root.video-path;
                    wrap: no-wrap;
                    overflow: elide;
                }
            }
            

            Rectangle {
                height: 5px;
            }

            Button {
                text: "添加任务";
                height: 40px;
                icon-width: 28px;
                icon-spacing: 10px;
                icon: @image-url("../assets/svg/add_circle.svg");
            }
        }
    }

}