import {  VerticalBox ,LineEdit, HorizontalBox} from "std-widgets.slint";
import { Button } from "../base/fluent/button.slint";
import { AppData } from "../store.slint";
import { Page } from "../widget/Page.slint";

export component AddPage inherits Page {

    VerticalLayout{

        HorizontalBox {
            padding: 0px;
            spacing: 10px;
            Button {
                // border-radius: 5px;
                text:"设置封面";
                clicked => { AppData.router = "home" }
            }
            Button {
                // border-radius: 5px;
                text:"选择视频";
            }
        }
    
        Text {
            font-size: 12px;
            text: "123";
            wrap: no-wrap;
            width: 300px;
            height: 14px;
        }

    
        LineEdit {       
            height: 40px;
            enabled:true;
        }



        popup := PopupWindow {
            Rectangle { height:100%; width: 100%; background: yellow; }
            x: 20px; y: 20px; height: 50px; width: 50px;
        }

        TouchArea {
            // height:100%; width: 100%;
            clicked => { popup.show(); }
        }

    }
}