import {  VerticalBox ,LineEdit, HorizontalBox,StandardTableView,GroupBox} from "std-widgets.slint";
import { Btn } from "../compiler/button.slint";
import {MaterialFontSettings, MaterialPalette,Elevation } from "../theme.slint";
export component HomePage inherits VerticalLayout {
    padding: 0px;
    height: 518px;
    spacing: 10px;

    Btn {
        height: 40px;
        border-radius: 5px;
        text:"添加任务";
    }
    Btn {
        height: 40px;
        border-radius: 5px;
        text:"开始任务";
    }
    
        
    Rectangle  {
        border-radius: 5px;
        border-color: MaterialPalette.border;
        border-width: 1px;
        // Text {text: "1111111111111111111111111111111111111111111123";}
        VerticalLayout {
            padding: 10px;
            // height: 100%;
            StandardTableView {
                // height: 100%;
                padding: 0px;
                width: 100%;
                columns: [
                    { title: "Header 1",horizontal_stretch:1 },
                    { title: "speed",width:50px, },
                ];
                rows: [
                    [
                        { text: "Item 1" }, { text: "Item 1" },
                    ],
                    [
                        { text: "Item 2" }, { text: "Item 2" },
                    ],
                    [
                        { text: "Item 3" }, { text: "Item 3" },
                    ],
                    [
                        { text: "Item 1" }, { text: "Item 1" },
                    ],
                    [
                        { text: "Item 2" }, { text: "Item 2" },
                    ],
                    [
                        { text: "Item 3" }, { text: "Item 3" },
                    ],
                    [
                        { text: "Item 1" }, { text: "Item 1" },
                    ],
                    [
                        { text: "Item 2" }, { text: "Item 2" },
                    ],
                    [
                        { text: "Item 3" }, { text: "Item 3" },
                    ],
                    [
                        { text: "Item 1" }, { text: "Item 1" },
                    ],
                    [
                        { text: "Item 2" }, { text: "Item 2" },
                    ],
                    [
                        { text: "Item 3" }, { text: "Item 3" },
                    ],
                    [
                        { text: "Item 1" }, { text: "Item 1" },
                    ],
                    [
                        { text: "Item 2" }, { text: "Item 2" },
                    ],
                    [
                        { text: "Item 3" }, { text: "Item 31" },
                    ]
                ];
            }
        }

    }
    
}