import {  VerticalBox ,LineEdit, HorizontalBox,StandardTableView,GroupBox} from "std-widgets.slint";
import { Button } from "../compiler/fluent/button.slint";
import { StandardTableView } from "../compiler/fluent/tableview.slint";
import { FluentPalette } from "../compiler/fluent/styling.slint";
import { MaterialFontSettings, MaterialPalette,Elevation } from "../theme.slint";
export component HomePage inherits VerticalLayout {
    padding: 0px;
    height: 518px;
    spacing: 10px;

    Button {
        
        text:"添加任务";
    }
    Button {
        text:"开始任务";
    }
    
        
    Rectangle  {
        border-radius: 5px;
        border-color: FluentPalette.border;
        border-width: 1px;
        // Text {text: "1111111111111111111111111111111111111111111123";}
        VerticalLayout {
            padding: 10px;
            // height: 100%;
            StandardTableView {
                // height: 100%;
                padding: 0px;
                width: 100%;
                columns: [
                    { title: "文件", horizontal_stretch:1 },
                    { title: "进度", horizontal_stretch:1 },
                    { title: "操作", horizontal_stretch:1 },
                ];
                rows: [
                    [
                        { text: "Item 1" }, { text: "Item 1" },
                    ],
                    [
                        { text: "Item 2" }, { text: "Item 2" },
                    ],
                    [
                        { text: "Item 3" }, { text: "Item 3" },
                    ],
                    [
                        { text: "Item 1" }, { text: "Item 1" },
                    ],
                    [
                        { text: "Item 2" }, { text: "Item 2" },
                    ],
                    [
                        { text: "Item 3" }, { text: "Item 3" },
                    ],
                    [
                        { text: "Item 1" }, { text: "Item 1" },
                    ],
                    [
                        { text: "Item 2" }, { text: "Item 2" },
                    ],
                    [
                        { text: "Item 3" }, { text: "Item 3" },
                    ],
                    [
                        { text: "Item 1" }, { text: "Item 1" },
                    ],
                    [
                        { text: "Item 2" }, { text: "Item 2" },
                    ],
                    [
                        { text: "Item 3" }, { text: "Item 3" },
                    ],
                    [
                        { text: "Item 1" }, { text: "Item 1" },
                    ],
                    [
                        { text: "Item 2" }, { text: "Item 2" },
                    ],
                    [
                        { text: "Item 3" }, { text: "Item 31" },
                    ]
                ];
            }
        }

    }
    Button {text: "123";}
    
}