// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

import { FluentFontSettings, FluentPalette, Icons } from "styling.slint";
import { MenuBorder, ListItem, FocusBorder } from "components.slint";
import { ComboBoxBase } from "./common/combobox-color.slint";
import { bridge } from "../../bridge.slint";

import { ScrollView } from "std-widgets.slint";


export component ColorComboBox {
    in property <[color]> model <=> i-base.model;
    in property <bool> enabled <=> i-base.enabled;
    out property <bool> has-focus <=> i-base.has-focus;
    in-out property <int> current-index <=> i-base.current-index;
    in-out property <color> current-value <=> i-base.current-value;

    callback selected <=> i-base.selected;

    min-width: max(160px, i-layout.min-height);
    min-height: max(32px, i-layout.min-height);
    horizontal-stretch: 1;
    vertical-stretch: 0;
    
    
    

    states [
        disabled when !root.enabled : {
            i-background.background: FluentPalette.control-disabled;
            i-background.border-color: FluentPalette.border;
            i-text.color: FluentPalette.text-disabled;
            // i-icon.colorize: FluentPalette.text-disabled;
        }
        pressed when i-base.pressed : {
            i-background.background: FluentPalette.control-alt-tertiary;
            i-background.border-color: FluentPalette.border;
            i-text.color: FluentPalette.text-secondary;
            // i-icon.colorize: FluentPalette.text-tertiary;
        }
        hover when i-base.has-hover : {
            // i-background.background: red;
        }

        focused when i-text.has-focus : {
            i-background.background: FluentPalette.control-input-active;
            i-background.border-color: FluentPalette.border;
            i-focus-border.background: FluentPalette.accent-background;
        }

    ]




    i-base := ComboBoxBase {
        width: 100%;
        height: 100%;
        
        show-popup => {
            i-popup.show();
        }
    }

    i-background := Rectangle {
        border-radius: 3px;
        background: FluentPalette.control-background;
        border-width: 1px;
        border-color: FluentPalette.control-border;

        animate border-color { duration: 200ms; }

        i-layout := HorizontalLayout {
            padding-left: 11px;
            padding-right: 7px;
            spacing: 8px;

            i-text := TextInput {
                horizontal-alignment: left;
                vertical-alignment: center;
                font-size: FluentFontSettings.body.font-size;
                font-weight: FluentFontSettings.body.font-weight;
                color: FluentPalette.control-foreground;
                text: bridge.color-to-string(root.current-value);
                selection-background-color: FluentPalette.selection-background;
                selection-foreground-color: FluentPalette.accent-foreground;
                edited() => {
                    // i-icon.background = bridge.string-to-color(i-text.text);
                    root.current-value = bridge.string_to_color(i-text.text);
                }
            }

            i-color := VerticalLayout {
                alignment: center;
                i-icon := Rectangle{
                    width: 16px;
                    height: 16px;
                    border-color: FluentPalette.foreground;
                    padding: 1px;
                    border-width: 1px;
                    background: root.current-value;
                }    
            }

            
        }
        i-focus-border := Rectangle {
            x: parent.border-radius;
            y: parent.height - self.height;
            width: parent.width - 2 * parent.border-radius;
            height: 2px;
        }
    }

    // focus border
    // if (i-text.has-focus && root.enabled) : FocusBorder {
    //     border-radius: i-background.border-radius;
    // }

    i-popup := PopupWindow {
        x: 0;
        // Position the popup so that the first element is over the popup.
        // Ideally it should be so that the current element is over the popup.
        y: root.height+5px;
        width: root.width;
        height: 160px;
        MenuBorder {
            ScrollView {
                width: root.width;
                height: 160px;
                vertical-stretch: 1;
                VerticalLayout {
                    // padding: 4px;
                    spacing: 4px;
                    for value[index] in root.model : Rectangle {
                        height: root.height;
                        width: root.width;
                        background: value;
                    
                        i-touch-area := TouchArea {
                            clicked => {
                                i-base.select(index);
                                i-text.text = bridge.color_to_string(root.current-value);
                            }
                        }
                    }
                }
            }
        }
    }
}
