import {  VerticalBox , HorizontalBox,StandardTableView, Button} from "std-widgets.slint";
import { Button } from "./base/fluent/button.slint";
import { Header } from "./widget/Header.slint";
import { SideBar } from "./widget/SideBar.slint";

import { HomePage, AddPage, AboutPage } from "./page/index.slint";

import { AppData } from "./store.slint";
import { Page } from "widget/Page.slint";
import { Router } from "./widget/Router.slint";



export component MainWindow inherits Window {
    title: "VC Slint";
    
    width: 320px;
    height: 568px;
    default-font-size: 14px;
    icon: @image-url("./assets/slint.png");
    
    padding: 0px;


    in-out property router <=> AppData.router;
    

    VerticalLayout{
        padding-left: 10px;
        padding-right: 10px;
        padding-top: 0px;
        padding-bottom: 5px;
        alignment: start;
        spacing: 0px;

        Header {}
        
        Router {
            height: 518px;
            HomePage {
                router: "add";
            }
            AddPage {
                router: "home";
            }
            AboutPage {
                router: "about";
            }
        }
    }

    side-bar := SideBar {
        title: "Menu";
        model: [
            { name:"Home", router: "home" },
            { name:"About", router: "about" }
        ];
    }
}
