import {  VerticalBox , HorizontalBox,StandardTableView, Button} from "std-widgets.slint";
import { Button } from "./compiler/fluent/button.slint";
import { Header } from "./widget/Header.slint";
import { SideBar } from "./widget/SideBar.slint";

import { HomePage } from "page/HomePage.slint";
import { AddPage } from "page/AddPage.slint";
import { AppData } from "./store.slint";
import { Page } from "widget/Page.slint";



export component MainWindow inherits Window {
    title: "VC Slint";
    
    width: 320px;
    height: 568px;
    default-font-size: 14px;
    icon: @image-url("./assets/slint.png");
    
    padding: 0px;


    in-out property router <=> AppData.router;
    

    VerticalLayout{
        padding-left: 10px;
        padding-right: 10px;
        padding-top: 0px;
        padding-bottom: 5px;
        alignment: start;
        spacing: 0px;

        Header {}
        Rectangle {
            height: 518px;
            HomePage { x: 0;}
            AddPage { x: root.width;}
        }

        // AddPage { isShow: router == "add";}
    }

    side-bar := SideBar {
        title: "Menu";
        model: ["Controls"];
    }
}
